/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/auth/AuthForm.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Command: typeof import('./src/components/ui/command/Command.vue')['default']
    CommandDialog: typeof import('./src/components/ui/command/CommandDialog.vue')['default']
    CommandEmpty: typeof import('./src/components/ui/command/CommandEmpty.vue')['default']
    CommandGroup: typeof import('./src/components/ui/command/CommandGroup.vue')['default']
    CommandInput: typeof import('./src/components/ui/command/CommandInput.vue')['default']
    CommandItem: typeof import('./src/components/ui/command/CommandItem.vue')['default']
    CommandList: typeof import('./src/components/ui/command/CommandList.vue')['default']
    CommandSeparator: typeof import('./src/components/ui/command/CommandSeparator.vue')['default']
    CommandShortcut: typeof import('./src/components/ui/command/CommandShortcut.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    IconLucideCandyCane: typeof import('~icons/lucide/candy-cane')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down')['default']
    IconLucideChevronUpDown: typeof import('~icons/lucide/chevron-up-down')['default']
    IconLucidePartyPopper: typeof import('~icons/lucide/party-popper')['default']
    IconLucideSpinner: typeof import('~icons/lucide/spinner')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
